### ISSUE TITLE
Matomo 3.5.1 missing

### ISSUE THREAD

**Issue by floek** [matomo-org/docker#102]
Hi Matomo,

can't get Matomo 3.5.1 tag as docker image.
Is it planed to support all patches?

Greetings,
Floek

**Comment by mcnesium** [comment]
[Configure automated builds from GitHub](https://docs.docker.com/docker-hub/github/)

**Comment by J0WI** [comment]
https://github.com/docker-library/official-images/commit/5a1820529f332b7d903fdd8e75cb84aaa5ea0cb2

**Comment by floek** [comment]
Hi,

it's not yet working for me:
`
# docker pull matomo:3.5.1-fpm
3.5.1-fpm: Pulling from library/matomo
no matching manifest for linux/amd64 in the manifest list entries
`

Any suggestions?

Thank you

Floek

**Comment by J0WI** [comment]
That seems to affect only the `fpm` variant, see #104.

**Comment by talberkoSB** [comment]
not working for me also

**Comment by tianon** [comment]
It was a flaky build (race condition in `gpg` code); I've hit it with the hammer until we got lucky (so builds should be up now), and will be sending a PR to adjust the `Dockerfile` to be slightly more proactive about the race. :+1:
