### ISSUE TITLE
No matching manifest for linux/amd64

### ISSUE THREAD

**Issue by diesl** [matomo-org/docker#104]
I tried to go from 3.5.0 to 3.5.1 and got this error when i tried to pull the image:
> Pulling app (matomo:fpm)...
 fpm: Pulling from library/matomo
 ERROR: no matching manifest for linux/amd64 in the manifest list entries

**Comment by J0WI** [comment]
@tianon this does only affect the FPM variant, but https://github.com/docker-library/official-images/blob/master/library/matomo#L11 LGTM.
Is something wrong with the build process?

**Comment by floek** [comment]
See #102

**Comment by talberkoSB** [comment]
I get it also.

**Comment by tianon** [comment]
It was a flaky build (race condition in `gpg` code); I've hit it with the hammer until we got lucky (so builds should be up now), and will be sending a PR to adjust the `Dockerfile` to be slightly more proactive about the race. :+1:
