### ISSUE TITLE
Docker Pull Not Giving Version 3.6.0

### ISSUE THREAD

**Issue by cloudmanic** [matomo-org/docker#115]
Hi,

I am trying to upgrade to 3.6.0 via docker. Below show my output showing I am getting 3.5.x

https://gist.github.com/cloudmanic/3e607ef19e8d6b98211ad81a341e4f56

This suggests 3.6.0 should work. 

https://github.com/matomo-org/docker/commit/ff4908d348b3bf08ac3e6fa82ff76b3f69790e6d

This suggest maybe docker hub has not synced. 

https://hub.docker.com/r/library/matomo/tags/

Thanks.
~Spicer

**Comment by SeydouConte** [comment]
Hi, 
I have the dame problem!
Thank you !

**Comment by rapidsteve** [comment]
ditto

**Comment by nikolaidenissov** [comment]
same problem

**Comment by diesl** [comment]
@tianon Maybe you can help to fix this? Thanks!

**Comment by nikolaidenissov** [comment]
anybody here?

**Comment by hthetiot** [comment]
Please publish 3.6 image

**Comment by hthetiot** [comment]
I published 3.6-apache:
- https://hub.docker.com/r/sylaps/matomo/

```
git clone git@github.com:matomo-org/docker.git matomo-docker
cd matomo-docker
cd apache 
docker build . -t matomo:latest
docker tag matomo:latest  sylaps/matomo:3.6-apache
docker push sylaps/matomo:3.6-apache
```

**Comment by ciliusmp** [comment]
Same here.

**Comment by hthetiot** [comment]
My image is public if  you need it in the mean time:
- git pull sylaps/matomo:3.6-apache

**Comment by tianon** [comment]
Looks like automation was broken by https://github.com/matomo-org/docker/pull/112 -- it'll either need to be reverted, adjusted, or `generate-stackbrew-library.sh` updated to take it into account.

**Comment by hthetiot** [comment]
Thanks @tianon

**Comment by iffyuva** [comment]
folks, thanks for bringing this to my notice. Will the PR #116 help?

**Comment by pierreozoux** [comment]
It should be fixed with last commit.

**Comment by rapidsteve** [comment]
> It should be fixed with last commit.

It's not.

**Comment by diesl** [comment]
It's available on Docker Hub now. Thanks to everybody who helped to resolve this issue 👍

**Comment by julien1619** [comment]
I'm using the docker image `matomo:fpm-alpine` in docker compose and I've pulled all images today to upgrade it. However, after installing the last image (`pull`, `down` then `up`), Matomo keeps saying that the 3.6.0 update is available and that I have the outdated version 3.5.1.

I've checked in the environment variables and I have `MATOMO_VERSION` set to `3.6.0` but it doesn't seem to be consistent with the version really installed in the container.

What information could help you to figure it out?

**Comment by J0WI** [comment]
Did you mount a volume with old Matomo code?

**Comment by julien1619** [comment]
Yes, that's it! Thank you!

I'm using docker compose v3 and `volumes_from` is not available anymore, I had to create a named volume. However the behavior is different than before, the data are persistent inside the volume, and not read in the container as it was the case with v2. That's why it's not working as expected for me.
