### ISSUE TITLE
Why does the entrypoint copy the source?

### ISSUE THREAD

**Issue by sj26** [matomo-org/docker#129]
Hi there! This might be a silly question, but why does the entry point copy the source into the www volume? Volumes are initialised from the underlying layer contents.

**Comment by tianon** [comment]
> Volumes are initialised from the underlying layer contents.

Not if they're a bind mount of a directory from the host. :wink:

**Comment by sj26** [comment]
Ah. That seems like a bit of an anti-pattern? The docker image should contain the application being run, the volumes should ideally contain configuration and data only. Or is that a problem with the mixed nature of this php application with plugins?

**Comment by sj26** [comment]
(I'm running matomo on Fargate as stateless containers, which has been a lot of trouble with configs and plugins and trackers being written everywhere)

**Comment by J0WI** [comment]
Matomo can update itself and there are many ways to customize it. That's why we use the whole www as volume.

**Comment by sj26** [comment]
Right. Relying on a shared file system makes autoscaling setups pretty tricky. Is there any interest in developing a stateless Docker packaging without shared file system for autoscaling setups?

**Comment by J0WI** [comment]
You can use more specific volume mounts (some examples are discussed in #89 or #97).
Some Environment variables are supported by https://github.com/matomo-org/matomo/pull/13676 and https://github.com/matomo-org/plugin-EnvironmentVariables, PRs to enhance this are welcomed.

**Comment by sj26** [comment]
🙇
