### ISSUE TITLE
Make use of Github releases

### ISSUE THREAD

**Issue by thomasleveil** [matomo-org/docker#130]
Could you please make use of git tags and/or Github release? This would allow us to get notification on new releases : 
![image](https://user-images.githubusercontent.com/42300/50042013-f9896380-005d-11e9-8672-761c33b26768.png)

**Comment by J0WI** [comment]
The docker image has no releases, it's just rebuilded from time to time. We use the [stable releases of Matomo](https://github.com/matomo-org/matomo/releases), you can subscribe there.
