### ISSUE TITLE
Rebuild needed on Docker Hub

### ISSUE THREAD

**Issue by Saboteur777** [matomo-org/docker#138]
The latest available tag for official Matomo Docker Hub image is 3.7: https://hub.docker.com/_/matomo?tab=tags 

Please tag a new Docker image to include version 3.8.

**Comment by jakejarvis** [comment]
Yes, please – sounds like there are some pretty critical security fixes in 3.8!

**Comment by zaggash** [comment]
Shall we ask to go to 3.8.1 directly or is there a PR for it aswell ?

**Comment by Findus23** [comment]
3.8.1 will be released very soon, so I'd say building 3.8.1 directly should be possible

**Comment by zaggash** [comment]
Actually the update reminder on my homepage, tell me it is available, but since I'm using Docker images, I can't update tho ;)

**Comment by J0WI** [comment]
> Actually the update reminder on my homepage tell me it is available, but since I'm using Docker images, I can't update tho ;)

You actually can update Matomo even inside Docker.

**Comment by zaggash** [comment]
What about static files in the image if my container get rescheduled ?

**Comment by J0WI** [comment]
You need to use a persistent volume to keep the files.

**Comment by zaggash** [comment]
I agree to keep the config in a volume, but what about website static files, possibly new needed packages in the image.
Update a container app through an UI when using Docker is not a best practice.

**Comment by crazy-max** [comment]
> Update a container app through an UI when using Docker is not a best practice.

@zaggash Totally agree, that's why I've created an [other image](https://github.com/crazy-max/docker-matomo) for Matomo beacause of this.

See also this issue on the main repo (matomo-org/matomo#12988) to try to solve this but they do not agree with my statement (matomo-org/docker#97) unfortunately.

**Comment by zaggash** [comment]
That is unfortunate.
At this point the image is not designed to run on a cluster as is.
@crazy-max Did you try to persist the plugin folder ? what is the drawback ?

**Comment by crazy-max** [comment]
@zaggash Everything is persisted as intended (configuration, installed plugins (not core ones), tmp, sessions and user folders to store your custom logo). Ready to go on a cluster, see [swarm and k8s examples](https://github.com/crazy-max/docker-matomo/tree/master/examples).
For plugins I have to use inotify to [watch and move plugins](https://github.com/crazy-max/docker-matomo/blob/master/assets/usr/local/bin/matomo_watch_plugins) in data folder...

**Comment by J0WI** [comment]
Closed by https://github.com/docker-library/official-images/pull/5345
