### ISSUE TITLE
Project Description is not Updated to Matomo

### ISSUE THREAD

**Issue by Fvbor** [matomo-org/docker#143]
Hey Guys,
not a big or important "bug", the project description is Docker for Piwik, not Docker for Matomo.
But maybe has somebody a minute free to fix it

![image](https://user-images.githubusercontent.com/18524580/52182228-610c9580-27fb-11e9-9ec1-ef31a4fd806e.png)

Have a nice day

**Comment by J0WI** [comment]
@mattab could you help with this?

**Comment by mattab** [comment]
Sure, should be done :+1:
