### ISSUE TITLE
Allow increasing PHP's limits

### ISSUE THREAD

**Issue by djmaze** [matomo-org/docker#144]
We are seeing fatal errors such as the following when querying longer time ranges:

`Allowed memory size of 16777216 bytes exhausted`

There should be a way to increase the PHP memory limit in the container, [as described in the FAQ](https://matomo.org/docs/setup-auto-archiving/#increase-php-memory-limit).

**Comment by djmaze** [comment]
Addendum: It should be possible to increase / disable the `max_execution_time` as well.

**Comment by J0WI** [comment]
It is possible, but we are using the default values:
https://github.com/docker-library/wordpress/issues/10#issuecomment-122659326

**Comment by tholu** [comment]
@J0WI Not sure why you closed this issue, as this is unsolved and a problem for larger sites deployed via Docker.

**Comment by J0WI** [comment]
Would you like to provide a patch similar to https://github.com/nextcloud/docker/pull/1379?

**Comment by bauera-hk** [comment]
i just had the same issue.
is there any persistent way in changing the limits?
my only workaround is changing the settings inside the running container and do a "service apache2 reload"
