### ISSUE TITLE
server reached pm.max_children setting (5), consider raising it

### ISSUE THREAD

**Issue by brijoyj** [matomo-org/docker#152]
Any idea how we can address this issue? We are seeing the errors in logs when the matomo receives more data "server reached pm.max_children setting (5), consider raising it"

After reviewing the https://github.com/docker-library/php/issues/162#issuecomment-174020731 recommendation 
We also have the following details
grep -vE '^;|^ *$' /usr/local/etc/php-fpm.d/www.conf.default
[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

Not sure what other settings we should try?

**Comment by J0WI** [comment]
You can mount your own config into `/usr/local/etc/php-fpm.d/` or, if you use `docker-compose` [scale](https://docs.docker.com/compose/reference/scale/) the amount of FPM containers.
