### ISSUE TITLE
Does the "GeoIP 2 (Php)" configuration shares IPs with a third party?

### ISSUE THREAD

**Issue by kelson42** [matomo-org/docker#153]
I use Matomo in a Docker instance and have my instance configure with "GeoIP 2 (Php)". I'm pretty concerned that my visitor information are shared with a third party (Maximind?). Is that the case or everything runs locally?

**Comment by fdellwing** [comment]
Matomo uses a free database downloaded from Maxmind to do geolocation. No visitor IPs will be send to Maxmind.

**Comment by kelson42** [comment]
@fdellwing Thank you for the clarification.
