### ISSUE TITLE
Requesting v3 of docker-compose.yml

### ISSUE THREAD

**Issue by ambroiseRabier** [matomo-org/docker#155]
Can we have https://github.com/matomo-org/docker/blob/master/.examples/nginx/docker-compose.yml in v3 version ? `volumes_from` is not supported anymore. How do I replace it? And why do we need to share the same volumes between nginx and matomo anyway?

**Comment by J0WI** [comment]
> And why do we need to share the same volumes between nginx and matomo anyway?

The PHP-FPM variant does only process PHP files. All static files are served directly by nginx.
