### ISSUE TITLE
docker-compose.yaml file with mysql/mariadb

### ISSUE THREAD

**Issue by ORESoftware** [matomo-org/docker#170]
quite curious to know if there is a docker-compose.yml file that I can steal that has an db instance and a matomo instance all linked-up etc.

if not, this is a request for someone who knows more than me to create one and put it in this repo?

**Comment by ORESoftware** [comment]
I found one here:
https://github.com/bitnami/bitnami-docker-matomo.git

maybe link to it from this project's readme?

**Comment by makeworld-the-better-one** [comment]
That's a lot better, thanks for sharing!

**Comment by J0WI** [comment]
We already have an example: https://github.com/matomo-org/docker/tree/master/.examples/apache
