### ISSUE TITLE
apache running in fpm container? what is the port to expose

### ISSUE THREAD

**Issue by ORESoftware** [matomo-org/docker#174]
Sorry if this is a dupe question. I have this:

```
docker run --rm -d -p 443:443 -p 80:8080 -v "$data_dir":'/var/www/html' --name interos-matomo interos-matomo
```

but the health check at:

```
GET /
```

is not healthy.  So is apache in the matomo container listening on 80 or 8080 or?
I tried 

```
-p 80:80
```

and

```
-p 80:8080
```

neither seems to work

**Comment by J0WI** [comment]
The FPM service runs on port `9000`. You have to connect this container to a web server (or a web server container): https://github.com/matomo-org/docker/tree/master/.examples/nginx
