### ISSUE TITLE
Make default tag using nginx

### ISSUE THREAD

**Issue by alexanderadam** [matomo-org/docker#192]
It would probably make sense to use Nginx instead of Apache as it usually consumes less resources and therefore less electricity/money/CO2/…

I guess [the image of crazy-max](https://github.com/crazy-max/docker-matomo) is probably a good starting point.

**Comment by SuperSandro2000** [comment]
I would rather add a note about this in the README to not create issues with existing installations.

**Comment by J0WI** [comment]
PHP-FPM and nginx are two different services and therefore two different images. Please use the [FPM variant](https://github.com/matomo-org/docker/tree/master/.examples/nginx) for nginx.
