### ISSUE TITLE
"MySQL server has gone away" error

### ISSUE THREAD

**Issue by ThibaultVlacich** [matomo-org/docker#208]
If I'm using exactly the example as present here: https://github.com/matomo-org/docker/tree/master/.examples/apache, I'm getting this error at the step "3. Database Setup".

> Error while trying to connect to the database server: SQLSTATE[HY000] [2006] MySQL server has gone away.

I followed [this article](https://fr.matomo.org/faq/troubleshooting/faq_183/) with no success, still getting this error.

**Comment by SirTerrific** [comment]
Hi,
Did you resolve this issue ? I have the same ... right now.

**Comment by mattab** [comment]
please see this FAQ for solutions to "Mysql server gone away": https://matomo.org/faq/troubleshooting/faq_183/
