### ISSUE TITLE
Missing 3.14.1 version image tags

### ISSUE THREAD

**Issue by davidlemaitre** [matomo-org/docker#213]
Matomo 3.14.1 has been released on September 10. Following that release, Docker images has been updated as well but the 3.14.1 and 3.14.1-* tags are missing. If I pull the latest image version, the environment variable MATOMO_VERSION is 3.14.0 not 3.14.1.

**Comment by J0WI** [comment]
Please see https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what and https://github.com/docker-library/official-images/pull/8738
