### ISSUE TITLE
matomo 4 images

### ISSUE THREAD

**Issue by zuozp8** [matomo-org/docker#221]
as matomo4 is already in RC stage, it would be nice to have docker images with it to be able to try it out

**Comment by mikaello** [comment]
The Dockerfiles was [updated with version `4.0.0` two days ago](https://github.com/matomo-org/docker/commit/052259cbea76220d2be52d2f9931ae4b85a941e7), but I can't find the `4.0.0` tag on [docker hub](https://hub.docker.com/_/matomo?tab=tags&page=1&ordering=last_updated). From the build/test pipeline it does not seem that it is pushed anywhere: https://github.com/matomo-org/docker/runs/1444602519 , so I guess this is a manual job.

**Comment by J0WI** [comment]
Same as https://github.com/matomo-org/docker/issues/213#issuecomment-694329141

**Comment by mikaello** [comment]
So it seems we are waiting for this to be merged: https://github.com/docker-library/official-images/pull/9187/files

**Comment by mikaello** [comment]
> So it seems we are waiting for this to be merged: [docker-library/official-images#9187](https://github.com/docker-library/official-images/pull/9187)

The pull request is now merged, and Matomo v4 is now avaliable from docker hub https://hub.docker.com/_/matomo?tab=tags&page=1&ordering=last updated 🎉

**Comment by houfu** [comment]
Reading this: https://matomo.org/docs/update/ -- It looks possible that replacing the image  (and following through with database upgrade if necessary) is enough to upgrade to matomo 4. Is that actually true? I have not found upgrade instructions for version 4 for docker.

**Comment by KopfKrieg** [comment]
> Is that actually true?

In short: Yes.

Last weekend I upgraded from `matomo:3-apache` to `matomo:4-apache` and everything went fine. I recommend looking through all your options/settings once you've upgraded to make sure you didn't miss anything (and a database schema upgrade might be required, but Matomo will tell you how, so nothing to worry about).
