### ISSUE TITLE
Docker image vulnerabilities

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/docker#361]
Hi Team,

there is currently an impressive list of vulnerabilities listed here: https://artifacthub.io/packages/helm/bitnami/matomo?modal=security-report
about our Docker image.

Would it be possible to have a look at it?

**Comment by sgiehl** [comment]
The bitnami image isn't created by us. So there isn't much we can do. You can try to create a report here instead: https://github.com/bitnami/charts/tree/main/bitnami/matomo
