### ISSUE TITLE
Monitoring https sites

### ISSUE THREAD

**Issue by uschtwill** [matomo-org/docker#49]
What is the best practice to monitor https sites? 

My scenario: I am running Drupal and other stuff in containers on a dockerhost, with external traffic coming in via an nginx reverse proxy (https://github.com/jwilder/nginx-proxy), which takes care of https/ssl/letsencrypt too. I would like to not unnecessarily expose Piwik externally. 

The [piwik module](https://www.drupal.org/project/piwik) in Drupal seems to be able to connect to the piwik-nginx via http just fine, but apparently requires the traffic between Drupal and itself to be https, if the site itself is run on https. It says `The URL to your Piwik base directory with SSL certificate installed. Required if you track a SSL enabled website. Example: "https://www.example.com/piwik/".` under the textfield where the piwik address goes. 

But even with (self-signed) certificates, it fails, throwing `The validation of "https://monitoring_piwik-nginx_1/piwik.php" failed with error "Error opening socket connection ssl://monitoring_piwik-nginx_1:443" (HTTP code 0)` (translated).

It looks to me like its simply not happy with the self-signed certificates. Now, before I dig deeper or just expose Piwik externally, I am wondering if there is a best practice for monitoring https sites with a dockerized Piwik? And is the behaviour of requiring the site-piwik traffic to be https when the site is running https the same for other frameworks, or is it just a Drupal quirk?

**Comment by uschtwill** [comment]
I just found two more hints about this:

- https://piwik.org/faq/general/faq_68/. And going to `https://url/to/piwik/piwik.php?rec=1&idsite=1` does throw the error `NET::ERR_CERT_AUTHORITY_INVALID`, as expected. So yeah... no self-signed certificates.
- https://stackoverflow.com/questions/9533799/why-is-it-not-possible-to-track-an-https-site-from-an-http-piwik-site. And this sounds like it is not possible to just flip a switch somewhere and force piwik to use http regardless, even if in a Docker environment this would be unproblematic?!

Seeing as I don't want to buy a certificate and letsencyrpt won't be able to reach the piwik-nginx, if its not exposed, it looks like I need to expose Piwik externally after all?

Is this reasoning sound or am I missing something?

**Comment by uschtwill** [comment]
Anyone? :)

**Comment by J0WI** [comment]
There is a upstream supported Docker container for [certbot](https://hub.docker.com/r/certbot/certbot/), so you can use e.g. standalone, webroot or dns vailidation methods to get a valid cert. This container need to be exposed, at least temporary.
The cert must be stored in a volume that is accessible by the Matomo webserver or proxy, but it's not necessary to expose it.
