### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [matomo-org/docker#67]
I want to build this image on arm64 architecture but I'm not sure this tar.gz file can be support arm64 architecture. So the file of tar.gz whether or not support arm64.

**Comment by gardner** [comment]
Did you try it?

**Comment by gardner** [comment]
Looks like you need to change two parts of the piwik `Dockerfile`. The first line should be changed to `FROM arm32v7/php:5.6-fpm` and the `x86_64-linux-gnu` part needs to be changed to `arm-linux-gnueabihf` for the compilation to succeed.

I pushed an example with a readme file here: https://github.com/gardner/docker-piwik/blob/master/arm32v7/readme.md

It doesn't really fit with the existing docker-piwik build script so I'm not sure it deserves a pull request yet. Hopefully it helps you.

**Comment by longquan7** [comment]
@gardner I want to support arm64v8 not arm32v7

**Comment by longquan7** [comment]
@gardner  I was use arm64v8/php:5.6-fpm and the x86_64-linux-gnu changed to aarch64-linux-gnueabihf,but when RUN pecl install APCu geoip was tips:No releases available for package "pecl.php.net/APCu"and No releases available for package "pecl.php.net/geoip"

**Comment by gardner** [comment]
Yeah, it seems like arm support in docker really isn't great yet. I had trouble getting the fpm version working. I am not a maintainer of piwik, just an interested individual like yourself. I can't offer any more help because I don't have the time. 

You are on the right path with `arm64v8/php`. I just can't go with you any further. Good luck!

**Comment by gardner** [comment]
Maybe the piwik maintainers like @michaelze or @tianon are interested in officially supporting arm.

**Comment by gardner** [comment]
@longquan7 I suggest doing tests with docker-compose and then submit a pull request to this repo.

**Comment by longquan7** [comment]
@gardner OK ,thanks for your help

**Comment by pierreozoux** [comment]
Hello!

Yes PR is more than welcome!
Here, can you check [this section](https://github.com/docker-library/official-images#multiple-architectures) to prepare our repo for that please?

Thanks!

**Comment by longquan7** [comment]
@pierreozoux When I was build on arm64 architecture, when "RUN pecl install APCu geoip",there is a problem that No releases available for package "pecl.php.net/APCu" and No releases available for package "pecl.php.net/geoip" .
