### ISSUE TITLE
Container is running on port 80 by default

### ISSUE THREAD

**Issue by nik-garmash** [matomo-org/docker#69]
Readme says that it runs on port 9000 and user need proxy, but in reality, it runs on port 80 out of the box.

```bash
docker run --name test-piwik --link test-mysql:db -d piwik
```

Results in

```bash
26b8a4fef4a6        piwik               "/entrypoint.sh ap..."   Less than a second ago   Up 2 seconds        80/tcp   test-piwik
```

Not sure if the readme needs to be fixed or default configuration.

**Comment by AleksandarIvanov7887** [comment]
Found out that after 3.0.1 version, they separated the docker image in two: `-apache` & `-fpm`
Adding -fpm to the version would result in running on port 9000.
Link here : https://hub.docker.com/_/piwik/
