### ISSUE TITLE
Any way to use with piwik-log-analytics?

### ISSUE THREAD

**Issue by bufke** [matomo-org/docker#72]
It seems like piwik-log-analytics is intended to run on the same server as the piwik installation itself. Using it with docker seems challenging. Has anyone had any success? What I'd love to do is have the aggregated logs from a dockerized app analyzed in piwki (also in docker). Perhaps doing a scheduled docker run that installs python, the script, downloads the logs, and processes them.

**Comment by juliencarnot** [comment]
Agree, see #46 . I still think this feature should be part of the official image.

**Comment by bufke** [comment]
I ended up just using the api instead of the log analytics - it seemed too confusing getting log analytics to work in a docker based environment.

**Comment by juliencarnot** [comment]
According to @J0WI "The Python script should be run in a [Python container](https://hub.docker.com/_/python/) (e.g. `python:2-alpine`)", I'm guessing using a link with the db container and a volume to mount the logs? I haven't seen docker-compose examples of this but it would be interesting to add an example or to document this recommended model.

**Comment by J0WI** [comment]
I think docker-compose is for services, but this script is a simple oneshot. You can start with this example:
`docker run --rm -v some-piwik-volume:/var/www/html -v some-logs:/some-logs --link some-piwik:piwik python:2-alpine python /var/www/html/misc/log-analytics/import_logs.py --url=piwik --login=example --password=example /some-logs`

**Comment by juliencarnot** [comment]
a "Docker-compose examples and log import instructions" section has been added to [README.md](https://github.com/matomo-org/docker/blob/master/README.md)...
