### ISSUE TITLE
default fpm settings too low

### ISSUE THREAD

**Issue by mstenz** [matomo-org/docker#76]
Hi, i have just used piwik:fpm and found out that the page reacts extremely slow. 
I found out that the pm.max_children setting is set to 5 (this is also reflected in the log:
`piwik-app.1.igu79lj18tix@cl01-n02    | [06-Jan-2018 01:10:18] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it`
as this is hardcoded in the image I either need to bound a volume and change the www.conf file but normally i don't want to do this and instead it should be increased already with the image or by any parameter. Is this possible please?

**Comment by J0WI** [comment]
See https://github.com/docker-library/php/issues/162#issuecomment-174020731.
Mounting your own config is the right way to go.
As an alternative, you can run multiple FPM containers and balance the load in your proxy.
