### ISSUE TITLE
Version 3.4 missing at Docker Hub/Store

### ISSUE THREAD

**Issue by diesl** [matomo-org/docker#92]
Hi,

would it be possible to publish Piwik/Matomo 3.4.0 on Docker Hub/Store? Right now, the newest listed version is 3.3.0. Seems like the update script that was mentioned in #43 did not run automatically as it is supposed.

Thanks!

P.S.: Maybe you should rename Piwik to Matomo on Docker Hub/Store or get in contact with the Docker staff to do it?

**Comment by Silvenga** [comment]
In progress via https://github.com/docker-library/official-images/pull/4196.

**Comment by juliencarnot** [comment]
Fixed, https://hub.docker.com/_/piwik/ is now deprecated by https://hub.docker.com/_/matomo/
