### ISSUE TITLE
Matomo 3.5.0 Docker image missing

### ISSUE THREAD

**Issue by jkoehne** [matomo-org/docker#98]
Due to GDPR we need to update our system to version 3.5.0 but it is not yet available on Docker Hub
https://hub.docker.com/_/matomo/

Any idea when it will be ready? We need the "consent" methods in order to be GDPR compliant.

**Comment by mcnesium** [comment]
[Configure automated builds from GitHub](https://docs.docker.com/docker-hub/github/)

**Comment by pierreozoux** [comment]
@tianon How can I see if the `update.sh` script was run from your bot?

**Comment by tianon** [comment]
https://doi-janky.infosiftr.net/job/update.sh/job/matomo/

(Looks like it's failing due to the protected branch.)

**Comment by diesl** [comment]
Matomo 3.5.0 is available on Docker Hub now.

**Comment by J0WI** [comment]
Considering as resolved.
