### ISSUE TITLE
File integrity check failed: vendor/maxmind-db/reader/autoload.php

### ISSUE THREAD

**Issue by mcnesium** [matomo-org/docker#99]
Thank you for updating the image ( #98 ). On multiple instances I experience this error, after updating to v3.5 using `image: matomo` in the compose file.

    Files were found in your Matomo but we didn't expect them.
    --> Please delete these files to prevent errors. <--

    File to delete: vendor/maxmind-db/reader/autoload.php

    To delete all these files at once, you can run this command:
    rm "/var/www/html/vendor/maxmind-db/reader/autoload.php"

**Comment by coderb** [comment]
i'm seeing this too.  i'm also unable to get geoip2 working (city level).  i install and configure it under settings/geolocation and it show me the city of my ip but on the dash i only get region level stats.  wondering if this is related.

**Comment by Findus23** [comment]
Hi,

This file has just been missed from the build process. It shouldn't change anything apart from the integrity check warning.
It has also been solved in Matomo 3.5.1.

See also https://github.com/matomo-org/matomo/issues/12883

**Comment by J0WI** [comment]
Release of 3.5.1 has been made, so I'm closing this.
